'use client';

import { type ReactNode, useState } from 'react';
import { encoder, toBase64, toHex } from '../crypto';
import type { ProcessStep, Tone } from '../types';

const tones: Record<Tone, string> = { success: 'border-lime-300/30 bg-lime-300/10 text-lime-100', warning: 'border-amber-300/30 bg-amber-300/10 text-amber-100', danger: 'border-rose-300/30 bg-rose-300/10 text-rose-100', neutral: 'border-teal-300/30 bg-teal-300/10 text-teal-100' };
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: Tone }) { return <span className={`inline-flex rounded border px-2 py-1 font-mono text-[10px] ${tones[tone]}`}>{children}</span>; }
export function Button({ children, onClick, secondary = false, disabled = false }: { children: ReactNode; onClick: () => void; secondary?: boolean; disabled?: boolean }) { return <button type="button" disabled={disabled} onClick={onClick} className={secondary ? 'rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-xs font-bold disabled:opacity-40' : 'rounded-lg bg-lime-200 px-3 py-2 text-xs font-extrabold text-[#062321] disabled:opacity-40'}>{children}</button>; }
export function Section({ title, kicker, children }: { title: string; kicker: string; children: ReactNode }) { return <section className="mx-auto max-w-6xl"><p className="mb-2 font-mono text-[10px] tracking-[.18em] text-teal-200">{kicker}</p><h1 className="m-0 text-4xl font-extrabold tracking-tight md:text-5xl">{title}</h1>{children}</section>; }
export function Notice({ children, tone }: { children: ReactNode; tone: Tone }) { return <div className={`rounded-xl border p-3 text-xs leading-5 ${tones[tone]}`}>{children}</div>; }
export function Info({ label, value }: { label: string; value: string }) { return <div><dt className="font-mono text-[9px] uppercase text-slate-500">{label}</dt><dd className="text-xs text-slate-200">{value}</dd></div>; }
export function BytesViewer({ label, value }: { label: string; value: string }) { const [view, setView] = useState<'Texto' | 'HEX' | 'Base64'>('Texto'); const bytes = encoder.encode(value); const output = view === 'Texto' ? value : view === 'HEX' ? toHex(bytes) : toBase64(bytes); return <article className="mt-4 rounded-xl border border-white/10 bg-black/20 p-3"><div className="flex items-center justify-between gap-2"><strong className="text-xs">{label}</strong><div>{(['Texto', 'HEX', 'Base64'] as const).map((item) => <button type="button" onClick={() => setView(item)} className={`ml-1 rounded px-2 py-1 font-mono text-[9px] ${view === item ? 'bg-teal-200 text-[#062321]' : 'text-slate-400'}`} key={item}>{item}</button>)}</div></div><code className="mt-2 block max-h-28 overflow-auto break-all rounded bg-black/30 p-2 font-mono text-[10px] text-teal-100">{output}</code><small className="mt-2 block text-[10px] text-slate-500">{bytes.length} bytes</small></article>; }
export function Process({ steps, active, onSelect }: { steps: ProcessStep[]; active: number; onSelect: (index: number) => void }) { const current = steps[active]!; return <><div className="my-5 flex gap-2 overflow-auto">{steps.map((step, index) => <button type="button" onClick={() => onSelect(index)} className={`min-w-32 rounded-xl border p-3 text-left ${active === index ? 'border-lime-200 bg-lime-200/10' : 'border-white/10 bg-black/20'}`} key={step.title}><span className="font-mono text-[9px] text-teal-100">{index + 1}</span><strong className="mt-1 block text-xs">{step.title}</strong></button>)}</div><article className="rounded-xl border border-white/10 bg-black/20 p-4"><Badge>{current.algorithm || current.title}</Badge><p className="mt-3 text-xs leading-5 text-slate-300">{current.detail}</p>{current.data && <code className="mt-3 block break-all rounded bg-black/30 p-2 font-mono text-[10px] text-teal-100">{current.data}</code>}{current.property && <p className="mt-3 text-xs text-lime-100">Propriedade: {current.property}</p>}</article></>; }
export function TechnicalDetails({ algorithm, input, output, property }: { algorithm: string; input: string; output: string; property: string }) { return <details className="mt-4 rounded-xl border border-teal-300/20 bg-teal-300/5"><summary className="cursor-pointer p-3 text-xs font-bold text-teal-100">Detalhes técnicos</summary><dl className="grid gap-3 border-t border-teal-300/20 p-4 sm:grid-cols-2"><Info label="Algoritmo" value={algorithm} /><Info label="Entrada" value={input} /><Info label="Saída" value={output} /><Info label="Propriedade" value={property} /></dl></details>; }
